/** Chrome extension download metadata for the business panel.
 * FALLBACK only — prefer GET /api/extension/latest or /downloads/extension-meta.json.
 * Regenerated by: npm run sync:ext-version
 */
export const EXTENSION_DOWNLOAD_URL = "/downloads/iranexpedia-extension.zip";
export const EXTENSION_DOWNLOAD_NAME = "iranexpedia-extension.zip";

/** Fallback if API / meta are unreachable. Synced from config/extension.json */
export const EXTENSION_VERSION_FALLBACK = "7.7.4";

export type ExtensionMeta = {
  version: string;
  file: string;
  download_path?: string;
};
